# --- Этап сборки ---
    FROM node:18 AS build
    WORKDIR /app
    
    # Копируем package-файлы и устанавливаем зависимости
    COPY package.json package-lock.json ./
    RUN npm install
    RUN npm install webpack --save-dev
    RUN npm install react-router
    
    # Копируем оставшиеся файлы проекта
    COPY . .
    
    # Строим production-сборку
    RUN npm run build
    
    # --- Этап продакшн-сервера ---
    FROM nginx:alpine
    
    # Копируем собранную статику из предыдущего этапа
    COPY --from=build /app/build /usr/share/nginx/html
    
    
    EXPOSE 80
    
    CMD ["nginx", "-g", "daemon off;"]
    